2022-11-23 13:15:37,179 INFO    StreamThr :6812 [internal.py:wandb_internal():88] W&B internal server running at pid: 6812, started at: 2022-11-23 13:15:37.178086
2022-11-23 13:15:37,184 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: status
2022-11-23 13:15:37,189 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: status
2022-11-23 13:15:37,193 DEBUG   SenderThread:6812 [sender.py:send():303] send: header
2022-11-23 13:15:37,193 INFO    WriterThread:6812 [datastore.py:open_for_write():75] open: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221123_131537-2asmxbrp\run-2asmxbrp.wandb
2022-11-23 13:15:37,258 DEBUG   SenderThread:6812 [sender.py:send():303] send: run
2022-11-23 13:15:37,789 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: check_version
2022-11-23 13:15:37,802 INFO    SenderThread:6812 [dir_watcher.py:__init__():216] watching files in: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221123_131537-2asmxbrp\files
2022-11-23 13:15:37,802 INFO    SenderThread:6812 [sender.py:_start_run_threads():928] run started: 2asmxbrp with start time 1669205737.176084
2022-11-23 13:15:37,802 DEBUG   SenderThread:6812 [sender.py:send():303] send: summary
2022-11-23 13:15:37,803 INFO    SenderThread:6812 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-23 13:15:37,803 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: check_version
2022-11-23 13:15:37,911 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: run_start
2022-11-23 13:15:37,917 DEBUG   HandlerThread:6812 [meta.py:__init__():34] meta init
2022-11-23 13:15:37,917 DEBUG   HandlerThread:6812 [meta.py:__init__():49] meta init done
2022-11-23 13:15:37,918 DEBUG   HandlerThread:6812 [meta.py:probe():215] probe
2022-11-23 13:15:37,935 DEBUG   HandlerThread:6812 [meta.py:_setup_git():205] setup git
2022-11-23 13:15:38,010 DEBUG   HandlerThread:6812 [meta.py:_setup_git():212] setup git done
2022-11-23 13:15:38,010 DEBUG   HandlerThread:6812 [meta.py:_save_pip():53] save pip
2022-11-23 13:15:38,011 DEBUG   HandlerThread:6812 [meta.py:_save_pip():67] save pip done
2022-11-23 13:15:38,012 DEBUG   HandlerThread:6812 [meta.py:probe():253] probe done
2022-11-23 13:15:38,187 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:15:38,188 DEBUG   SenderThread:6812 [sender.py:send():303] send: files
2022-11-23 13:15:38,188 INFO    SenderThread:6812 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2022-11-23 13:15:38,190 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:15:38,397 DEBUG   SenderThread:6812 [sender.py:send():303] send: telemetry
2022-11-23 13:15:38,769 INFO    Thread-29 :6812 [upload_job.py:push():143] Uploaded file C:\Users\adams\AppData\Local\Temp\tmpokarnawqwandb\2o2r0hm8-wandb-metadata.json
2022-11-23 13:15:38,816 INFO    Thread-23 :6812 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221123_131537-2asmxbrp\files\wandb-summary.json
2022-11-23 13:15:38,817 INFO    Thread-23 :6812 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221123_131537-2asmxbrp\files\requirements.txt
2022-11-23 13:15:38,817 INFO    Thread-23 :6812 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221123_131537-2asmxbrp\files\wandb-metadata.json
2022-11-23 13:15:38,818 INFO    Thread-23 :6812 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221123_131537-2asmxbrp\files\output.log
2022-11-23 13:15:40,847 INFO    Thread-23 :6812 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221123_131537-2asmxbrp\files\output.log
2022-11-23 13:15:53,415 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:15:53,415 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:16:08,088 INFO    Thread-23 :6812 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221123_131537-2asmxbrp\files\config.yaml
2022-11-23 13:16:08,637 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:16:08,637 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:16:08,816 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:16:23,851 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:16:23,851 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:16:43,874 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:16:57,373 ERROR   SenderThread:6812 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002309D38F460>, 'Connection to api.wandb.ai timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002309D38F460>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal_api.py", line 213, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002309D38F460>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))
2022-11-23 13:17:00,748 WARNING FileStreamThread:6812 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)). func: <bound method Session.post of <requests.sessions.Session object at 0x000002309CFB4670>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2asmxbrp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-23 13:17:03,897 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:17:23,920 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:17:23,977 WARNING FileStreamThread:6812 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2asmxbrp/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002309D3B5970>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002309CFB4670>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2asmxbrp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-23 13:17:43,928 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:17:49,978 WARNING FileStreamThread:6812 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2asmxbrp/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002309D4966D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002309CFB4670>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2asmxbrp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-23 13:18:03,952 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:18:23,965 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:18:38,972 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:18:38,972 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:18:39,560 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:18:39,934 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:18:39,934 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:18:40,379 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:18:40,820 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:18:40,820 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:18:41,509 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:18:41,509 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:18:43,996 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:18:43,996 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:18:54,375 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:18:59,635 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:18:59,635 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:19:15,276 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:19:15,276 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:19:27,503 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:19:31,656 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:19:31,656 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:19:51,664 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:19:55,278 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:20:00,509 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:20:10,497 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:20:10,497 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:20:30,518 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:20:44,118 ERROR   SenderThread:6812 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002309D4A1340>, 'Connection to api.wandb.ai timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002309D4A1340>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal_api.py", line 213, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002309D4A1340>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))
2022-11-23 13:20:50,545 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:21:04,653 WARNING FileStreamThread:6812 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)). func: <bound method Session.post of <requests.sessions.Session object at 0x000002309CFB4670>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2asmxbrp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-23 13:21:10,566 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:21:11,586 WARNING FileStreamThread:6812 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2asmxbrp/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002309D4A88E0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002309CFB4670>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2asmxbrp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-23 13:21:17,432 WARNING FileStreamThread:6812 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2asmxbrp/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002309D4CBB50>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002309CFB4670>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2asmxbrp/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-23 13:21:30,595 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:21:50,612 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:21:57,537 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:21:57,722 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:21:57,722 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:21:57,901 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:21:57,902 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:21:58,102 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:21:58,292 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:21:58,292 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:22:10,629 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:22:10,629 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:22:12,388 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:22:25,816 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:22:25,816 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:22:41,104 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:22:41,104 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:22:45,430 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:22:56,298 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:22:56,298 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:23:11,501 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:23:11,501 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:23:18,395 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:23:26,708 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:23:26,708 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:23:41,921 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:23:41,922 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:23:51,419 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:23:57,151 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:23:57,151 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:24:12,335 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:24:12,335 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:24:24,480 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:24:27,534 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:24:27,535 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:24:45,834 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:24:45,836 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:24:57,607 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:25:01,031 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:25:01,031 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:25:21,045 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:25:34,748 ERROR   SenderThread:6812 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002309D4CB1F0>, 'Connection to api.wandb.ai timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002309D4CB1F0>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal_api.py", line 213, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002309D4CB1F0>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))
2022-11-23 13:25:41,069 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:25:46,809 WARNING FileStreamThread:6812 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)). func: <bound method Session.post of <requests.sessions.Session object at 0x000002309CFB4670>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2asmxbrp/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 16, 'content': ['{"system.cpu": 30.29, "system.memory": 84.76, "system.disk": 33.5, "system.proc.memory.availableMB": 2473.45, "system.proc.memory.rssMB": 591.94, "system.proc.memory.percent": 3.65, "system.proc.cpu.threads": 56.0, "system.network.sent": 5012221, "system.network.recv": 65511320, "_wandb": true, "_timestamp": 1669206297.607877, "_runtime": 560.431793}']}}, 'dropped': 0}}
2022-11-23 13:26:01,085 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:26:09,975 WARNING FileStreamThread:6812 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2asmxbrp/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002309D4A1F70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002309CFB4670>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2asmxbrp/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 16, 'content': ['{"system.cpu": 30.29, "system.memory": 84.76, "system.disk": 33.5, "system.proc.memory.availableMB": 2473.45, "system.proc.memory.rssMB": 591.94, "system.proc.memory.percent": 3.65, "system.proc.cpu.threads": 56.0, "system.network.sent": 5012221, "system.network.recv": 65511320, "_wandb": true, "_timestamp": 1669206297.607877, "_runtime": 560.431793}']}}, 'dropped': 0}}
2022-11-23 13:26:21,098 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:26:35,101 WARNING FileStreamThread:6812 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2asmxbrp/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002309D4A1460>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002309CFB4670>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2asmxbrp/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 16, 'content': ['{"system.cpu": 30.29, "system.memory": 84.76, "system.disk": 33.5, "system.proc.memory.availableMB": 2473.45, "system.proc.memory.rssMB": 591.94, "system.proc.memory.percent": 3.65, "system.proc.cpu.threads": 56.0, "system.network.sent": 5012221, "system.network.recv": 65511320, "_wandb": true, "_timestamp": 1669206297.607877, "_runtime": 560.431793}']}}, 'dropped': 0}}
2022-11-23 13:26:41,126 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:26:44,072 WARNING FileStreamThread:6812 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2asmxbrp/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002309D4C62B0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002309CFB4670>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2asmxbrp/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 16, 'content': ['{"system.cpu": 30.29, "system.memory": 84.76, "system.disk": 33.5, "system.proc.memory.availableMB": 2473.45, "system.proc.memory.rssMB": 591.94, "system.proc.memory.percent": 3.65, "system.proc.cpu.threads": 56.0, "system.network.sent": 5012221, "system.network.recv": 65511320, "_wandb": true, "_timestamp": 1669206297.607877, "_runtime": 560.431793}']}}, 'dropped': 0}}
2022-11-23 13:27:01,163 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:27:02,859 WARNING FileStreamThread:6812 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2asmxbrp/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002309D4C62B0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002309CFB4670>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2asmxbrp/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 16, 'content': ['{"system.cpu": 30.29, "system.memory": 84.76, "system.disk": 33.5, "system.proc.memory.availableMB": 2473.45, "system.proc.memory.rssMB": 591.94, "system.proc.memory.percent": 3.65, "system.proc.cpu.threads": 56.0, "system.network.sent": 5012221, "system.network.recv": 65511320, "_wandb": true, "_timestamp": 1669206297.607877, "_runtime": 560.431793}']}}, 'dropped': 0}}
2022-11-23 13:27:11,885 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:27:12,066 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:27:12,067 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:27:12,254 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:27:12,464 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:27:12,465 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:27:12,657 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:27:12,658 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:27:13,061 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:27:13,248 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:27:21,173 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:27:21,173 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:27:36,365 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:27:36,365 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:27:42,835 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:27:51,580 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:27:51,580 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:28:06,796 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:28:06,796 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:28:15,924 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:28:21,991 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:28:21,991 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:28:37,203 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:28:37,203 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:28:48,943 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:28:52,428 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:28:52,429 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:29:07,657 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:29:07,657 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:29:21,924 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:29:22,847 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:29:22,847 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:29:38,062 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:29:38,062 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:29:53,278 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:29:53,278 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:29:54,887 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:30:08,497 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:30:08,497 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:30:23,691 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:30:23,691 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:30:27,881 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:30:38,965 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:30:38,965 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:30:54,183 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:30:54,183 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:31:00,948 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:31:09,377 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:31:09,377 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:31:24,564 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:31:24,564 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:31:33,913 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:31:39,781 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:31:39,781 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:31:55,193 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:31:55,193 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:31:57,474 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: partial_history
2022-11-23 13:31:57,478 DEBUG   SenderThread:6812 [sender.py:send():303] send: history
2022-11-23 13:31:57,479 DEBUG   SenderThread:6812 [sender.py:send():303] send: summary
2022-11-23 13:31:57,480 INFO    SenderThread:6812 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-23 13:31:57,676 INFO    Thread-23 :6812 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221123_131537-2asmxbrp\files\wandb-summary.json
2022-11-23 13:31:58,686 INFO    Thread-23 :6812 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221123_131537-2asmxbrp\files\output.log
2022-11-23 13:32:06,863 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:32:10,398 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:32:10,398 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:32:25,655 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:32:25,655 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:32:39,945 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:32:40,896 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:32:40,896 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:32:56,107 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:32:56,107 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:33:11,349 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:33:11,349 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:33:13,043 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:33:26,638 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:33:26,638 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:33:41,848 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:33:41,848 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:33:46,096 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:33:57,058 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:33:57,058 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:34:12,254 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:34:12,255 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:34:19,062 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:34:27,447 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:34:27,447 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:34:42,658 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:34:42,658 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:34:52,128 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:34:57,845 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:34:57,846 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:35:13,013 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:35:13,013 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:35:25,170 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:35:28,210 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:35:28,210 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:35:43,409 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:35:43,410 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:35:58,169 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:35:58,606 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:35:58,606 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:36:13,828 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:36:13,828 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:36:29,068 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:36:29,068 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:36:31,126 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:36:44,265 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:36:44,265 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:36:59,475 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:36:59,475 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:37:04,103 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:37:14,667 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:37:14,667 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:37:29,930 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:37:29,930 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:37:37,093 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:37:45,353 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:37:45,353 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:38:00,564 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:38:00,564 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:38:10,114 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:38:15,759 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:38:15,759 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:38:30,969 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:38:30,969 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:38:43,113 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:38:46,178 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:38:46,178 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:39:01,401 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:39:01,401 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:39:16,153 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:39:16,623 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:39:16,624 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:39:31,819 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:39:31,819 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:39:47,070 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:39:47,070 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:39:49,167 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:40:02,271 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:40:02,271 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:40:17,471 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:40:17,471 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:40:22,150 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:40:32,661 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:40:32,661 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:40:47,855 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:40:47,855 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:40:55,127 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:41:03,049 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:41:03,049 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:41:18,254 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:41:18,254 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:41:28,075 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:41:33,438 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:41:33,438 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:41:48,629 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:41:48,629 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:42:01,129 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:42:03,812 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:42:03,812 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:42:19,035 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:42:19,035 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:42:34,079 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:42:34,215 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:42:34,215 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:42:49,461 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:42:49,461 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:43:04,665 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:43:04,665 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:43:06,975 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:43:19,850 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:43:19,850 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:43:35,050 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:43:35,050 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:43:39,972 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:43:50,256 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:43:50,256 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:44:05,462 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:44:05,462 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:44:12,914 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:44:20,698 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:44:20,699 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:44:35,907 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:44:35,907 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
2022-11-23 13:44:46,005 DEBUG   SenderThread:6812 [sender.py:send():303] send: stats
2022-11-23 13:44:51,128 DEBUG   HandlerThread:6812 [handler.py:handle_request():138] handle_request: stop_status
2022-11-23 13:44:51,128 DEBUG   SenderThread:6812 [sender.py:send_request():317] send_request: stop_status
