2022-10-14 11:54:21,929	INFO trainable.py:160 -- Trainable.setup took 13.472 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2022-10-14 11:54:21,931	WARNING util.py:65 -- Install gputil for GPU system monitoring.
Main trainign step 0
training epoch 0 447 0.8 0.3979865771812083
Main trainign step 1
training epoch 1 636 0.8 0.6371069182389937
Main trainign step 2
training epoch 2 680 0.8 0.6598529411764705
Main trainign step 3
training epoch 3 689 0.8 0.6680696661828737
Main trainign step 4
training epoch 4 751 0.8 0.7324900133155791
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 172, in <module>
    res.append(wfun(a))
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 100, in my_experiment
    config.save #crash "A3CConfig has no attribute 'save'"
AttributeError: 'A3CConfig' object has no attribute 'save'
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 172, in <module>
    res.append(wfun(a))
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 100, in my_experiment
    config.save #crash "A3CConfig has no attribute 'save'"
AttributeError: 'A3CConfig' object has no attribute 'save'