2022-11-17 13:55:26,127 INFO    StreamThr :8252 [internal.py:wandb_internal():88] W&B internal server running at pid: 8252, started at: 2022-11-17 13:55:26.125967
2022-11-17 13:55:26,133 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: status
2022-11-17 13:55:26,137 DEBUG   SenderThread:8252 [sender.py:send_request():317] send_request: status
2022-11-17 13:55:26,144 DEBUG   SenderThread:8252 [sender.py:send():303] send: header
2022-11-17 13:55:26,144 INFO    WriterThread:8252 [datastore.py:open_for_write():75] open: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\run-2m0x8yhh.wandb
2022-11-17 13:55:26,178 DEBUG   SenderThread:8252 [sender.py:send():303] send: run
2022-11-17 13:55:26,636 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: check_version
2022-11-17 13:55:26,650 INFO    SenderThread:8252 [dir_watcher.py:__init__():216] watching files in: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files
2022-11-17 13:55:26,650 INFO    SenderThread:8252 [sender.py:_start_run_threads():928] run started: 2m0x8yhh with start time 1668689726.122964
2022-11-17 13:55:26,651 DEBUG   SenderThread:8252 [sender.py:send():303] send: summary
2022-11-17 13:55:26,651 INFO    SenderThread:8252 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-17 13:55:26,652 DEBUG   SenderThread:8252 [sender.py:send_request():317] send_request: check_version
2022-11-17 13:55:26,748 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: run_start
2022-11-17 13:55:26,757 DEBUG   HandlerThread:8252 [meta.py:__init__():34] meta init
2022-11-17 13:55:26,763 DEBUG   HandlerThread:8252 [meta.py:__init__():49] meta init done
2022-11-17 13:55:26,763 DEBUG   HandlerThread:8252 [meta.py:probe():215] probe
2022-11-17 13:55:26,779 DEBUG   HandlerThread:8252 [meta.py:_setup_git():205] setup git
2022-11-17 13:55:26,856 DEBUG   HandlerThread:8252 [meta.py:_setup_git():212] setup git done
2022-11-17 13:55:26,856 DEBUG   HandlerThread:8252 [meta.py:_save_pip():53] save pip
2022-11-17 13:55:26,861 DEBUG   HandlerThread:8252 [meta.py:_save_pip():67] save pip done
2022-11-17 13:55:26,861 DEBUG   HandlerThread:8252 [meta.py:probe():253] probe done
2022-11-17 13:55:27,049 DEBUG   SenderThread:8252 [sender.py:send():303] send: files
2022-11-17 13:55:27,049 INFO    SenderThread:8252 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2022-11-17 13:55:27,050 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:55:27,051 DEBUG   SenderThread:8252 [sender.py:send_request():317] send_request: stop_status
2022-11-17 13:55:27,246 DEBUG   SenderThread:8252 [sender.py:send():303] send: telemetry
2022-11-17 13:55:27,651 INFO    Thread-29 :8252 [upload_job.py:push():143] Uploaded file C:\Users\adams\AppData\Local\Temp\tmpclcbvw1_wandb\wituqphm-wandb-metadata.json
2022-11-17 13:55:27,660 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\output.log
2022-11-17 13:55:27,661 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\requirements.txt
2022-11-17 13:55:27,661 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\wandb-metadata.json
2022-11-17 13:55:27,662 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\wandb-summary.json
2022-11-17 13:55:29,671 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\output.log
2022-11-17 13:55:42,252 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:55:42,253 DEBUG   SenderThread:8252 [sender.py:send_request():317] send_request: stop_status
2022-11-17 13:55:47,067 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 13:55:47,069 DEBUG   SenderThread:8252 [sender.py:send():303] send: history
2022-11-17 13:55:47,070 DEBUG   SenderThread:8252 [sender.py:send():303] send: summary
2022-11-17 13:55:47,074 INFO    SenderThread:8252 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-17 13:55:47,820 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\wandb-summary.json
2022-11-17 13:55:49,826 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\output.log
2022-11-17 13:55:56,890 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\config.yaml
2022-11-17 13:55:57,470 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:55:57,470 DEBUG   SenderThread:8252 [sender.py:send_request():317] send_request: stop_status
2022-11-17 13:55:57,658 DEBUG   SenderThread:8252 [sender.py:send():303] send: stats
2022-11-17 13:56:09,694 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 13:56:09,696 DEBUG   SenderThread:8252 [sender.py:send():303] send: history
2022-11-17 13:56:09,697 DEBUG   SenderThread:8252 [sender.py:send():303] send: summary
2022-11-17 13:56:09,701 INFO    SenderThread:8252 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-17 13:56:09,982 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\wandb-summary.json
2022-11-17 13:56:11,996 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\output.log
2022-11-17 13:56:12,671 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:56:12,671 DEBUG   SenderThread:8252 [sender.py:send_request():317] send_request: stop_status
2022-11-17 13:56:27,884 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:56:27,884 DEBUG   SenderThread:8252 [sender.py:send_request():317] send_request: stop_status
2022-11-17 13:56:30,462 DEBUG   SenderThread:8252 [sender.py:send():303] send: stats
2022-11-17 13:56:36,643 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 13:56:36,645 DEBUG   SenderThread:8252 [sender.py:send():303] send: history
2022-11-17 13:56:36,645 DEBUG   SenderThread:8252 [sender.py:send():303] send: summary
2022-11-17 13:56:36,646 INFO    SenderThread:8252 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-17 13:56:37,231 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\wandb-summary.json
2022-11-17 13:56:38,237 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\output.log
2022-11-17 13:56:43,095 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:56:43,095 DEBUG   SenderThread:8252 [sender.py:send_request():317] send_request: stop_status
2022-11-17 13:56:58,314 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:56:58,314 DEBUG   SenderThread:8252 [sender.py:send_request():317] send_request: stop_status
2022-11-17 13:57:03,214 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 13:57:03,216 DEBUG   SenderThread:8252 [sender.py:send():303] send: history
2022-11-17 13:57:03,217 DEBUG   SenderThread:8252 [sender.py:send():303] send: summary
2022-11-17 13:57:03,221 INFO    SenderThread:8252 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-17 13:57:03,431 DEBUG   SenderThread:8252 [sender.py:send():303] send: stats
2022-11-17 13:57:03,471 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\wandb-summary.json
2022-11-17 13:57:04,482 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\output.log
2022-11-17 13:57:06,488 INFO    Thread-23 :8252 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\adams\OneDrive\Documents\GitHub\Mavi\wandb\run-20221117_135526-2m0x8yhh\files\output.log
2022-11-17 13:57:13,527 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:57:13,528 DEBUG   SenderThread:8252 [sender.py:send_request():317] send_request: stop_status
2022-11-17 13:57:28,732 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:57:28,732 DEBUG   SenderThread:8252 [sender.py:send_request():317] send_request: stop_status
2022-11-17 13:57:32,258 ERROR   SenderThread:8252 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000024C7AD516A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024C7AD516A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal_api.py", line 213, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024C7AD516A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-11-17 13:57:33,302 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 13:57:48,753 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:58:02,852 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 13:58:05,153 WARNING FileStreamThread:8252 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024C7A9806D0>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2m0x8yhh/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-17 13:58:07,351 WARNING FileStreamThread:8252 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2m0x8yhh/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024C7AE979D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024C7A9806D0>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2m0x8yhh/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-17 13:58:08,758 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:58:12,274 WARNING FileStreamThread:8252 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2m0x8yhh/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024C7AE97A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024C7A9806D0>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2m0x8yhh/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-17 13:58:20,328 WARNING FileStreamThread:8252 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2m0x8yhh/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024C7AE97580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024C7A9806D0>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2m0x8yhh/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-17 13:58:28,761 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:58:31,857 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 13:58:38,888 WARNING FileStreamThread:8252 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2m0x8yhh/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024C7AE979D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024C7A9806D0>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2m0x8yhh/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-17 13:58:48,774 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:58:59,683 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 13:59:08,793 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:59:18,415 WARNING FileStreamThread:8252 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2m0x8yhh/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024C7AE97A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024C7A9806D0>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2m0x8yhh/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-17 13:59:28,811 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 13:59:31,240 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 13:59:48,817 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:00:02,115 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:00:08,836 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:00:24,242 WARNING FileStreamThread:8252 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2m0x8yhh/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024C7AE97A60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024C7A9806D0>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2m0x8yhh/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-17 14:00:27,717 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:00:28,856 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:00:48,870 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:00:50,747 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:01:08,888 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:01:13,454 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:01:28,902 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:01:35,980 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:01:48,909 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:02:03,513 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:02:08,927 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:02:28,939 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:02:35,224 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:02:48,950 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:02:57,496 WARNING FileStreamThread:8252 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2m0x8yhh/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024C7AE97520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024C7A9806D0>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2m0x8yhh/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-17 14:03:04,902 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:03:08,962 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:03:28,976 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:03:29,262 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:03:48,988 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:03:53,500 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:04:09,002 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:04:17,338 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:04:29,027 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:04:41,172 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:04:49,044 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:05:05,145 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:05:09,062 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:05:29,074 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:05:29,270 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:05:49,087 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:05:53,395 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:06:09,107 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:06:17,244 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:06:29,122 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:06:41,137 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:06:49,142 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:07:05,308 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:07:09,161 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:07:29,178 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:07:29,872 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:07:49,184 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:07:54,193 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:08:09,189 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:08:10,643 WARNING FileStreamThread:8252 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2m0x8yhh/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024C7AE97A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024C7A9806D0>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2m0x8yhh/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-17 14:08:24,092 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:08:29,196 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:08:49,205 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:08:58,033 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:09:09,224 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:09:27,333 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:09:29,248 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:09:49,262 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:09:53,390 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:10:09,264 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:10:19,154 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:10:29,289 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:10:45,003 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:10:49,305 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:11:09,308 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:11:10,514 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:11:29,318 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:11:35,740 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:11:49,328 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:12:01,421 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:12:09,340 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:12:27,280 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:12:29,359 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:12:49,376 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:12:52,734 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:13:09,377 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:13:18,147 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:13:26,963 WARNING FileStreamThread:8252 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/adamb/my-test-project/2m0x8yhh/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024C7AE97190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000024C7A9806D0>>, args: ('https://api.wandb.ai/files/adamb/my-test-project/2m0x8yhh/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-11-17 14:13:29,385 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:13:43,052 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:13:49,401 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:14:07,884 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:14:09,416 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:14:29,433 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:14:37,588 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:14:49,447 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:15:09,466 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:15:09,858 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:15:29,494 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:15:37,915 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:15:49,511 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:16:02,839 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:16:09,531 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:16:27,288 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:16:29,544 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:16:49,562 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:16:51,538 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:17:09,586 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: stop_status
2022-11-17 14:17:16,059 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: partial_history
2022-11-17 14:17:18,074 DEBUG   HandlerThread:8252 [handler.py:handle_request():138] handle_request: poll_exit
