2022-10-18 15:01:06,729	INFO trainable.py:160 -- Trainable.setup took 24.519 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2022-10-18 15:01:06,737	WARNING util.py:65 -- Install gputil for GPU system monitoring.
Main training step 0
training epoch 0 94 0.8 -0.3659574468085107
Main training step 1
training epoch 1 288 0.8 0.6138888888888889
Main training step 2
training epoch 2 277 0.8 0.6440433212996389
Main training step 3
training epoch 3 302 0.8 0.6658940397350993
Main training step 4
training epoch 4 292 0.8 0.6551369863013699
['self', 'mode', 'state', 'agent', 'v', 'Q', 'pi', 'policy', 'v2Q', 'gamma', 'method_label', 'label']
  0%|                                                                                                                | 0/10 [00:00<?, ?it/s](2, 2)
[47m                  
[47m   [31m[49m*0*[39m         [47m   
[47m   [49m       A    [47m   
[47m   [49m            [47m   
[47m   [49m            [47m   
[47m                  
  0%|                                                                                                                | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 194, in <module>
    res.append(wfun(a)) # i think this call the function that crashes
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 134, in my_experiment
    train(env, VINNetwork(env, trainer,num_outputs=5, model_config=dict(custom_model=vin_label, use_lstm=False), name='hardcoded'), num_episodes=10) #train() is a function in agent.py that crashes
  File "C:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\irlc\ex01\agent.py", line 187, in train
    s = env.reset() #!s=train
  File "C:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\irlc\utils\video_monitor.py", line 82, in reset
    self.env2_.render()
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\gym\core.py", line 295, in render
    return self.env.render(mode, **kwargs)
  File "C:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\mazeenv\maze_environment.py", line 177, in render
    self._reset_display()
  File "C:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\mazeenv\maze_environment.py", line 260, in _reset_display
    self.display = gridworld_graphics_display.GraphicsGridworldDisplay(self.mdp, gridSize)
AttributeError: 'MazeEnvironment' object has no attribute 'mdp'
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 194, in <module>
    res.append(wfun(a)) # i think this call the function that crashes
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 134, in my_experiment
    train(env, VINNetwork(env, trainer,num_outputs=5, model_config=dict(custom_model=vin_label, use_lstm=False), name='hardcoded'), num_episodes=10) #train() is a function in agent.py that crashes
  File "C:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\irlc\ex01\agent.py", line 187, in train
    s = env.reset() #!s=train
  File "C:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\irlc\utils\video_monitor.py", line 82, in reset
    self.env2_.render()
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\site-packages\gym\core.py", line 295, in render
    return self.env.render(mode, **kwargs)
  File "C:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\mazeenv\maze_environment.py", line 177, in render
    self._reset_display()
  File "C:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\mazeenv\maze_environment.py", line 260, in _reset_display
    self.display = gridworld_graphics_display.GraphicsGridworldDisplay(self.mdp, gridSize)
AttributeError: 'MazeEnvironment' object has no attribute 'mdp'